package com.example.sera_application.presentation.viewmodel.reservation

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.sera_application.domain.model.Event
import com.example.sera_application.domain.model.EventReservation
import com.example.sera_application.domain.model.enums.ReservationStatus
import com.example.sera_application.domain.usecase.event.GetEventByIdUseCase
import com.example.sera_application.domain.usecase.reservation.CreateReservationUseCase
import com.google.firebase.auth.FirebaseAuth
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class CreateReservationViewModel @Inject constructor(
    private val getEventByIdUseCase: GetEventByIdUseCase,
    private val createReservationUseCase: CreateReservationUseCase
) : ViewModel() {

    private val _event = MutableStateFlow<Event?>(null)
    val event: StateFlow<Event?> = _event.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    fun loadEvent(eventId: String) {
        viewModelScope.launch {
            _isLoading.value = true
            _error.value = null
            try {
                val fetchedEvent = getEventByIdUseCase(eventId)
                _event.value = fetchedEvent
            } catch (e: Exception) {
                _error.value = "Failed to load event: ${e.message}"
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun createReservation(
        eventId: String,
        quantities: Map<String, Int>,
        onSuccess: (String) -> Unit,
        onError: (String) -> Unit
    ) {
        viewModelScope.launch {
            _isLoading.value = true

            val userId = FirebaseAuth.getInstance().currentUser?.uid
            if (userId == null) {
                onError("User not logged in")
                _isLoading.value = false
                return@launch
            }

            val totalSeats = quantities.values.sum()
            if (totalSeats == 0) {
                 onError("Please select at least one ticket")
                 _isLoading.value = false
                 return@launch
            }

            // Simplistic: Assuming generic seat logic for now.
            // Ideally we'd create separate reservations or one logic structure
            val reservation = EventReservation(
                reservationId = "", // Generated by backend
                eventId = eventId,
                userId = userId,
                seats = totalSeats,
                status = ReservationStatus.PENDING,
                createdAt = System.currentTimeMillis()
            )

            try {
                // Corrected call matching UseCase signature
                val result = createReservationUseCase(reservation)

                if (result) {
                     onSuccess("Reservation created successfully")
                } else {
                     onError("Reservation failed")
                }
            } catch (e: Exception) {
                onError(e.message ?: "Unknown error")
            } finally {
                _isLoading.value = false
            }
        }
    }
}
